### ISSUE TITLE
Make the hostname customizable

### ISSUE THREAD

**Issue by kirankt** [defenseunicorns/uds-idam#106] opened 2023-10-19 20:50 UTC
Currently the hostname is set to `keycloak.###ZARF_VAR_DOMAIN###`, but it makes sense to configure the hostname itself rather than only the domain.

**Comment by rjferguson21** [comment] 2023-10-19 20:58
Dupe of https://github.com/defenseunicorns/uds-idam/issues/105

**Closed by rjferguson21** 2023-10-19 20:58 UTC
